CREATE TABLE PESSOAS ( 
    ID SERIAL NOT NULL, 
    NOME VARCHAR(20) NOT NULL,
    CONTRATO_ID SERIAL NOT NULL, 
    INADIMPLENTE BOOLEAN NOT NULL, 
    DT_COMPLETO DATE, 
    PRIMARY KEY (ID)
);

CREATE TABLE CONTRATOS (
    ID SERIAL NOT NULL,
    VALOR_PARCELA FLOAT NOT NULL,
    PARCELAS INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PAGAMENTOS (
    ID SERIAL NOT NULL,
    PESSOA_ID SERIAL NOT NULL,
    DT_PAGAMENTO DATE NOT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO PESSOAS(NOME, CONTRATO_ID, INADIMPLENTE, DT_COMPLETO) VALUES
('Cristian Ghyprievy', '2', TRUE, NULL),
('Joana Cabel', '1', TRUE, NULL),
('John Serial', '3', TRUE, NULL),
('Michael Seven', '2', FALSE, '2021-09-25');

INSERT INTO CONTRATOS (VALOR_PARCELA, PARCELAS) VALUES
(150.00, 100),
(300.00, 48),
(550.00, 24),
(1000.00, 12);

INSERT INTO PAGAMENTOS (PESSOA_ID, DT_PAGAMENTO) VALUES
(4, '2021-09-01'),
(3, '2021-09-05'),
(1, '2021-09-19'),
(2, '2021-09-25')