SELECT P.NOME, EXTRACT(DAY FROM PAG.DT_PAGAMENTO) AS DIA_MES, C.VALOR_PARCELA
FROM PESSOAS AS P, CONTRATOS AS C, PAGAMENTOS AS PAG
WHERE P.INADIMPLENTE = TRUE AND P.CONTRATO_ID = C.ID AND P.ID = PAG.PESSOA_ID
GROUP BY P.NOME, C.VALOR_PARCELA, PAG.DT_PAGAMENTO
ORDER BY P.NOME